/// Flutter icons ArtemisDcsIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArtemisDcsIcons
///      fonts:
///       - asset: fonts/ArtemisDcsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ArtemisDcsIcons {
  ArtemisDcsIcons._();

  static const _kFontFam = 'ArtemisDcsIcons';
  static const String? _kFontPkg = null;

  static const IconData exitrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData woman = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData man = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData girl = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boy = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toddler = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top_arrow = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom_arrow = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hidden = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workstation = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_file = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seat = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reduce = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pdf_file = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passport = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move = IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light = IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData full_screen = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_file = IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData departures = IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrivals = IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bp = IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bt = IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm = IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_screen = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData player = IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restart = IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passportconfirm = IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData denyload = IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pc_reverse = IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pc = IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bt_printer = IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bp_printer = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer = IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unload = IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkin = IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deliver = IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData load = IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baggagesort = IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offloadreq = IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hot = IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rush = IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sortintable = IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_left = IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_right = IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkdisable = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkenable = IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiodisable = IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioenable = IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkinletter = IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boardingletter = IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData damage = IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forbid = IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fragile = IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pack = IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch = IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
