/// Flutter icons SeatMapIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SeatMapIcons
///      fonts:
///       - asset: fonts/SeatMapIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class SeatMapIcons {
  SeatMapIcons._();

  static const _kFontFam = 'SeatMapIcons';
  static const String? _kFontPkg = null;

  static const IconData basennet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData childtype = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crew = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData extra = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData femaletype = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infanttype = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jumpseat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locked = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maletype = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passengerwithtoddler = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reserved = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seat = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlocked = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vip = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_off = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
