name: {{project_name}}
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter



  cupertino_icons: ^1.0.8
  hooks_riverpod: ^3.2.1
  flutter_hooks:
  go_router: ^17.1.0
  get_it: ^9.2.0
  dio: ^5.9.1
  shared_preferences: ^2.2.0
  flutter_spinkit: ^5.2.2
  auto_size_text: ^3.0.0
  toastification: ^3.0.3
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  app_device_net_info: ^0.0.6
  objectbox: ^5.2.0
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  objectbox_generator: any


objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  #  output_dir: custom
  # Or optionally specify the lib and test output folder separately.
  output_dir:
    lib: core/database/generated
  #   test: other



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/data/
    - assets/sounds/
    - assets/fonts/
  fonts:
    - family: Consola
      fonts:
        - asset: assets/fonts/consola/Consola.ttf
    - family: ArtemisIcons
      fonts:
        - asset: assets/fonts/ArtemisIcons.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/opensans/OpenSans-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/opensans/OpenSans-SemiBoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/opensans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/opensans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

