name: {{project_name}}
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^7.0.1
  get_it: ^7.6.0
  freezed: ^2.3.4
  hooks_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get: ^4.6.5
  connectivity_plus: ^4.0.0
  signalr_netcore: ^1.3.3
  convert: ^3.1.1
  archive: ^3.3.7
  bot_toast: ^4.0.3
  artemis_ui_kit: ^0.0.14
  network_manager: ^0.1.14
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  url_launcher: ^6.1.11
  path_provider: ^2.0.15
  dio: ^4.0.6
  flutter_spinkit: ^5.2.0
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  artemis_utils: ^0.0.6
  flutter_vector_icons: ^2.0.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/data/
    - assets/sounds/
    - assets/fonts/
  fonts:
    - family: ArtemisIcons
      fonts:
        - asset: assets/fonts/ArtemisIcons.ttf
    - family: SeatMapIcons
      fonts:
        - asset: assets/fonts/SeatMapIcons.ttf
    - family: ArtemisDcsIcons
      fonts:
        - asset: assets/fonts/ArtemisDcsIcons.ttf
    - family: BrsIcons
      fonts:
        - asset: assets/fonts/BRSIcons.ttf
    - family: Consola
      fonts:
        - asset: assets/fonts/consola/Consola.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/opensans/OpenSans-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/opensans/OpenSans-SemiBoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/opensans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/opensans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Signika
      fonts:
        - asset: assets/fonts/signika/SignikaNegative-Regular.ttf
        - asset: assets/fonts/signika/SignikaNegative-Light.ttf
          weight: 200
        - asset: assets/fonts/signika/SignikaNegative-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/signika/SignikaNegative-Bold.ttf
          weight: 700

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  # output_dir: custom
  # Or optionally specify the lib and test output folder separately.
  output_dir:
    lib: core/data_base
  #   test: other

msix_config:
  display_name: {{project_name.titleCase()}}
  publisher_display_name: ABOMIS Innovations Inc.
  identity_name: ABOMISInnovationsInc.AbomisDCS
  publisher: CN=2F524553-90DB-4FE5-B917-C1F735CC041B
  msix_version: 1.0.0.0
  icons_background_color: "#ffffff"
  architecture: x64
  capabilities: "internetClient"

  store: false
  #  publisher: CN=BF212345-5644-46DF-8668-012044C1B138
  languages: "en-us"
#  logo_path: "LOGO PATH HERE"
#  output_path: "OUTPUT PATH HERE"
  output_name: {{project_name.titleCase()}} Installer
#  app_installer: #<-- app installer configuration
#    publish_folder_path: "PubFolderPath"
#    hours_between_update_checks: 0
#    automatic_background_task: false
#    update_blocks_activation: false
#    show_prompt: true
#    force_update_from_any_version: false
