name: {{project_name}}
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependency_overrides:
  intl: ^0.20.1
  package_info_plus: ^8.1.2
  device_info_plus: ^11.2.0
  archive: ^4.0.2
  flutter_svg: ^2.0.9
  analyzer: ^6.5.0
  get_it: ^8.0.3



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: 14.2.0
  get_it: ^8.0.3
  freezed: ^2.5.7
  hooks_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  get: ^4.6.6
  connectivity_plus: ^6.1.1
  signalr_netcore: ^1.4.0
  convert: ^3.1.2
  archive: ^4.0.2
  bot_toast: ^4.1.3
  artemis_ui_kit: ^0.0.19
  network_manager: ^0.1.36
  shared_preferences: ^2.3.5
  intl: ^0.20.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  dio: ^5.7.0
  flutter_spinkit: ^5.2.1
  #  isar: ^3.1.0+1
  #  isar_flutter_libs: ^3.1.0+1
  artemis_utils: ^0.0.20
  flutter_vector_icons: ^2.0.0
  package_info_plus: ^8.1.2
  device_info_plus: ^11.2.0
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.4
  cached_network_image: ^3.4.1
  icons_plus: ^5.0.0
  tree_navigation: ^1.1.1
  ferry: ^0.16.1+2
  gql_http_link: ^1.1.0
  hive_flutter: ^1.1.0
  ferry_hive_store: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  ferry_generator: ^0.12.0+2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/data/
    - assets/sounds/
    - assets/fonts/
  fonts:
    - family: ArtemisIcons
      fonts:
        - asset: assets/fonts/ArtemisIcons.ttf
    - family: SeatMapIcons
      fonts:
        - asset: assets/fonts/SeatMapIcons.ttf
    - family: ArtemisDcsIcons
      fonts:
        - asset: assets/fonts/ArtemisDcsIcons.ttf
    - family: BrsIcons
      fonts:
        - asset: assets/fonts/BRSIcons.ttf
    - family: Consola
      fonts:
        - asset: assets/fonts/consola/Consola.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/opensans/OpenSans-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/opensans/OpenSans-SemiBoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/opensans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/opensans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Signika
      fonts:
        - asset: assets/fonts/signika/SignikaNegative-Regular.ttf
        - asset: assets/fonts/signika/SignikaNegative-Light.ttf
          weight: 200
        - asset: assets/fonts/signika/SignikaNegative-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/signika/SignikaNegative-Bold.ttf
          weight: 700
